# Form implementation generated from reading ui file 'TvControllerGui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 600))
        MainWindow.setMaximumSize(QtCore.QSize(300, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 261, 231))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.onButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.onButton.setGeometry(QtCore.QRect(90, 300, 113, 32))
        self.onButton.setObjectName("onButton")
        self.offButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.offButton.setGeometry(QtCore.QRect(90, 510, 113, 32))
        self.offButton.setObjectName("offButton")
        self.volumeUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeUpButton.setGeometry(QtCore.QRect(30, 340, 113, 32))
        self.volumeUpButton.setObjectName("volumeUpButton")
        self.volumeDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeDownButton.setGeometry(QtCore.QRect(30, 410, 113, 32))
        self.volumeDownButton.setObjectName("volumeDownButton")
        self.channelUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelUpButton.setGeometry(QtCore.QRect(160, 340, 113, 32))
        self.channelUpButton.setObjectName("channelUpButton")
        self.channelDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelDownButton.setGeometry(QtCore.QRect(160, 410, 113, 32))
        self.channelDownButton.setObjectName("channelDownButton")
        self.muteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(90, 470, 113, 32))
        self.muteButton.setObjectName("muteButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TV"))
        self.onButton.setText(_translate("MainWindow", "On"))
        self.offButton.setText(_translate("MainWindow", "Off"))
        self.volumeUpButton.setText(_translate("MainWindow", "Volume +"))
        self.volumeDownButton.setText(_translate("MainWindow", "Volume -"))
        self.channelUpButton.setText(_translate("MainWindow", "Channel +"))
        self.channelDownButton.setText(_translate("MainWindow", "Channel -"))
        self.muteButton.setText(_translate("MainWindow", "Mute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
